jobs:
  - name: beta-provision
    type: runSh
    steps:
      - IN: beta-aws-creds
      - IN: beta-infra-repo
      - TASK:
        - script: ls -atr
        - script: ls -al IN/beta-infra-repo/beta-infra-repo/
        - script: IN/beta-infra-repo/beta-infra-repo/provision.sh

    on_success:
      - echo 'on success !!!!!'
    on_failure:
      - echo 'Failed job .... :('

  - name: build-microbase
    type: runSh
    steps:
      - IN: microbase-repo
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/microbase-repo/microbase-repo/build.sh
      - OUT: microbase-img
    on_success:
      - echo 'on success !!!!!'
    on_failure:
      - echo 'Failed job .... :('

  - name: build-api
    type: runSh
    steps:
      - IN: api-repo
      - IN: microbase-img
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/api-repo/api-repo/build.sh
      - OUT: api-img
    on_success:
      - echo 'on success !!!!!'
    on_failure:
      - echo 'Failed job .... :('

  - name: build-www
    type: runSh
    steps:
      - IN: www-repo
      - IN: microbase-img
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/www-repo/www-repo/build.sh
      - OUT: www-img
    on_success:
      - echo 'on success !!!!!'
    on_failure:
      - echo 'Failed job .... :('
