jobs:
  - name: beta-provision
    type: runSh
    steps:
      - IN: beta-aws-creds
      - IN: beta-infra-repo
      - TASK:
        - script: ls -atr
        - script: ls -al IN/beta-infra-repo/gitRepo/
        - script: IN/beta-infra-repo/beta-infra-repo/provision.sh

    on_success:
      - echo 'on success !!!!!'
    on_failure:
      - echo 'Failed job .... :('

  - name: build-microbase
    type: runSh
    steps:
      - IN: microbase-repo
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/microbase-repo/gitRepo/build.sh
      - OUT: microbase-img
    on_success:
      - echo 'on success !!!!!'
    on_failure:
      - echo 'Failed job .... :('

  - name: build-api
    type: runSh
    steps:
      - IN: api-repo
      - IN: microbase-img
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/api-repo/gitRepo/build.sh
      - OUT: api-img
    on_success:
      - echo 'on success !!!!!'
    on_failure:
      - echo 'Failed job .... :('

  - name: build-www
    type: runSh
    steps:
      - IN: www-repo
      - IN: microbase-img
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/www-repo/gitRepo/build.sh
      - OUT: www-img
    on_success:
      - echo 'on success !!!!!'
    on_failure:
      - echo 'Failed job .... :('

  - name: build-micro
    type: runSh
    steps:
      - IN: micro-repo
      - IN: microbase-img
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/micro-repo/gitRepo/build.sh
      - OUT: acs-img
      - OUT: autod-img
      - OUT: barge-img
      - OUT: braintree-img
      - OUT: certgen-img
      - OUT: charon-img
      - OUT: cron-img
      - OUT: dcl-img
      - OUT: ddc-img
      - OUT: ec2-img
      - OUT: ecs-img
      - OUT: email-img
      - OUT: gke-img
      - OUT: hipchat-img
      - OUT: hubspotSync-img
      - OUT: irc-img
      - OUT: ini-img
      - OUT: iscan-img
      - OUT: isync-img
      - OUT: jobRequest-img
      - OUT: jobTrigger-img
      - OUT: marshaller-img
      - OUT: nf-img
      - OUT: slack-img
      - OUT: stepExec-img
      - OUT: sync-img
      - OUT: timeTrigger-img
      - OUT: triton-img
      - OUT: versionTrigger-img
      - OUT: webhook-img
    on_success:
      - echo 'on success !!!!!'
    on_failure:
      - echo 'Failed job .... :('
