jobs:
  - name: provision
    type: runSh
    steps:
      - IN: betaCluster
      - IN: beta-infra-repo
      - TASK:
        - script: ls -al IN/beta-infra-repo/beta-infra-repo/
        - script: IN/beta-infra-repo/beta-infra-repo/provision.sh
