jobs:
  - name: beta-provision
    type: runSh
    steps:
      - IN: beta-aws-creds
      - IN: beta-infra-repo
      - TASK:
        - script: ls -atr
        - script: ls -al IN/beta-infra-repo/gitRepo/
        - script: IN/beta-infra-repo/beta-infra-repo/provision.sh

    on_success:
      - echo 'on success !!!!!'
    on_failure:
      - echo 'Failed job .... :('

  - name: build-microbase
    type: runSh
    steps:
      - IN: microbase-repo
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/microbase-repo/gitRepo/build.sh
      - OUT: microbase-img
    on_success:
      - echo 'on success !!!!!'
    on_failure:
      - echo 'Failed job .... :('

  - name: build-rdsbase
    type: runSh
    steps:
      - IN: rdsbase-repo
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/rdsbase-repo/gitRepo/build.sh
      - OUT: rdsbase-img
    on_success:
      - echo 'on success !!!!!'
    on_failure:
      - echo 'Failed job .... :('

  - name: man-rds
    type: manifest
    steps:
      - IN: rdsbase-img

  - name: deploy-beta-rds
    type: deploy
    steps:
      - IN: man-rds
      - IN: beta-rds-docOpts
      - IN: beta-clust
      - IN: beta-rds-lb
        applyTo:
          - manifest: man-rds  # manifest that contains image to connect to
            image: rdsbase-img # img to connect to inside the above manifest
            port: 6379         # containerPort to connect to
      - TASK: managed
        deployMethod: upgrade

  - name: build-nexec
    type: runSh
    steps:
      - IN: nexec-repo
      - IN: microbase-img
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/nexec-repo/gitRepo/build.sh
      - OUT: nexec-img
    on_success:
      - echo 'on success !!!!!'
    on_failure:
      - echo 'Failed job .... :('

  - name: man-nexec
    type: manifest
    steps:
      - IN: nexec-img

  - name: deploy-beta-nexec
    type: deploy
    steps:
      - IN: man-nexec
      - IN: beta-docOpts
      - IN: beta-prm
      - IN: beta-clust

  - name: build-api
    type: runSh
    steps:
      - IN: api-repo
      - IN: microbase-img
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/api-repo/gitRepo/build.sh
      - OUT: api-img
    on_success:
      - echo 'on success !!!!!'
    on_failure:
      - echo 'Failed job .... :('

  - name: build-www
    type: runSh
    steps:
      - IN: www-repo
      - IN: microbase-img
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/www-repo/gitRepo/build.sh
      - OUT: www-img
    on_success:
      - echo 'on success !!!!!'
    on_failure:
      - echo 'Failed job .... :('

  - name: man-www
    type: manifest
    steps:
      - IN: www-img
      - IN: www-params

  - name: deploy-beta-www
    type: deploy
    steps:
      - IN: man-www
      - IN: beta-www-docOpts
      - IN: beta-prm
      - IN: beta-clust
      - IN: beta-www-lb
        applyTo:
          - manifest: man-www
            image: www-img
            port: 443
      - TASK: managed
        deployMethod: upgrade

  - name: build-micro
    type: runSh
    steps:
      - IN: micro-repo
      - IN: microbase-img
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/micro-repo/gitRepo/build.sh
      - OUT: acs-img
      - OUT: autod-img
      - OUT: barge-img
      - OUT: braintree-img
      - OUT: certgen-img
      - OUT: charon-img
      - OUT: cron-img
      - OUT: dcl-img
      - OUT: ddc-img
      - OUT: ec2-img
      - OUT: ecs-img
      - OUT: email-img
      - OUT: gke-img
      - OUT: hipchat-img
      - OUT: hubspotSync-img
      - OUT: irc-img
      - OUT: ini-img
      - OUT: iscan-img
      - OUT: isync-img
      - OUT: jobRequest-img
      - OUT: jobTrigger-img
      - OUT: marshaller-img
      - OUT: nf-img
      - OUT: slack-img
      - OUT: stepExec-img
      - OUT: sync-img
      - OUT: timeTrigger-img
      - OUT: triton-img
      - OUT: versionTrigger-img
      - OUT: webhook-img
    on_success:
      - echo 'on success !!!!!'
    on_failure:
      - echo 'Failed job .... :('

  - name: man-nf
    type: manifest
    steps:
      - IN: nf-img
      - IN: nf-params

  - name: man-slack
    type: manifest
    steps:
      - IN: slack-img
      - IN: slack-params

  - name: man-email
    type: manifest
    steps:
      - IN: email-img
      - IN: email-params

  - name: man-hipchat
    type: manifest
    steps:
      - IN: hipchat-img
      - IN: hipchat-params

  - name: man-irc
    type: manifest
    steps:
      - IN: irc-img
      - IN: irc-params

  - name: man-webhook
    type: manifest
    steps:
      - IN: webhook-img
      - IN: webhook-params

  - name: deploy-beta-notify
    type: deploy
    steps:
      - IN: man-nf
      - IN: man-slack
      - IN: man-email
      - IN: man-hipchat
      - IN: man-irc
      - IN: man-webhook
      - IN: beta-docOpts
      - IN: beta-prm
      - IN: beta-clust

  - name: man-barge
    type: manifest
    steps:
      - IN: barge-img
      - IN: barge-params

  - name: man-acs
    type: manifest
    steps:
      - IN: acs-img
      - IN: acs-params

  - name: man-autod
    type: manifest
    steps:
      - IN: autod-img
      - IN: autod-params

  - name: man-dcl
    type: manifest
    steps:
      - IN: dcl-img
      - IN: dcl-params

  - name: man-ddc
    type: manifest
    steps:
      - IN: ddc-img
      - IN: ddc-params

  - name: man-ecs
    type: manifest
    steps:
      - IN: ecs-img
      - IN: ecs-params

  - name: man-gke
    type: manifest
    steps:
      - IN: gke-img
      - IN: gke-params

  - name: man-triton
    type: manifest
    steps:
      - IN: triton-img
      - IN: triton-params

  - name: deploy-beta-pv1
    type: deploy
    steps:
      - IN: man-barge
      - IN: man-acs
      - IN: man-autod
      - IN: man-dcl
      - IN: man-ddc
      - IN: man-ecs
      - IN: man-gke
      - IN: man-triton
      - IN: beta-docOpts
      - IN: beta-prm
      - IN: beta-clust

  - name: man-charon
    type: manifest
    steps:
      - IN: charon-img
      - IN: charon-params

  - name: man-deploySteps
    type: manifest
    steps:
      - IN: stepExec-img
      - IN: deploySteps-params

  - name: man-manifestSteps
    type: manifest
    steps:
      - IN: stepExec-img
      - IN: manifestSteps-params

  - name: man-releaseSteps
    type: manifest
    steps:
      - IN: stepExec-img
      - IN: releaseSteps-params

  - name: man-rSyncSteps
    type: manifest
    steps:
      - IN: stepExec-img
      - IN: rSyncSteps-params

  - name: man-timeTrigger
    type: manifest
    steps:
      - IN: timeTrigger-img
      - IN: timeTrigger-params

  - name: man-versionTrigger
    type: manifest
    steps:
      - IN: versionTrigger-img
      - IN: versionTrigger-params

  - name: deploy-beta-pv2
    type: deploy
    steps:
      - IN: man-charon
      - IN: man-deploySteps
      - IN: man-manifestSteps
      - IN: man-releaseSteps
      - IN: man-rSyncSteps
      - IN: man-timeTrigger
      - IN: man-versionTrigger
      - IN: beta-docOpts
      - IN: beta-prm
      - IN: beta-clust

  - name: man-sync
    type: manifest
    steps:
      - IN: sync-img
      - IN: sync-params

  - name: man-marshaller
    type: manifest
    steps:
      - IN: marshaller-img
      - IN: marshaller-params

  - name: man-jobTrigger
    type: manifest
    steps:
      - IN: jobTrigger-img
      - IN: jobTrigger-params

  - name: man-jobRequest
    type: manifest
    steps:
      - IN: jobRequest-img
      - IN: jobRequest-params

  - name: man-hubspotSync
    type: manifest
    steps:
      - IN: hubspotSync-img
      - IN: hubspotSync-params

  - name: man-cron
    type: manifest
    steps:
      - IN: cron-img
      - IN: cron-params

  - name: man-certgen
    type: manifest
    steps:
      - IN: certgen-img
      - IN: certgen-params

  - name: man-braintree
    type: manifest
    steps:
      - IN: braintree-img
      - IN: braintree-params

  - name: deploy-beta-core
    type: deploy
    steps:
      - IN: man-sync
      - IN: man-marshaller
      - IN: man-jobTrigger
      - IN: man-jobRequest
      - IN: man-hubspotSync
      - IN: man-cron
      - IN: man-certgen
      - IN: man-braintree
      - IN: beta-docOpts
      - IN: beta-prm
      - IN: beta-clust

  - name: man-ini
    type: manifest
    steps:
      - IN: ini-img
      - IN: ini-params

  - name: man-ec2
    type: manifest
    steps:
      - IN: ec2-img
      - IN: ec2-params

  - name: deploy-beta-ci
    type: deploy
    steps:
      - IN: man-ini
      - IN: man-ec2
      - IN: beta-docOpts
      - IN: beta-prm
      - IN: beta-clust
