jobs:
  - name: beta-provision
    type: runSh
    steps:
      - IN: beta-aws-creds
      - IN: beta-infra-repo
      - TASK:
        - script: sudo apt-get install -y jq
        - script: IN/beta-infra-repo/gitRepo/build.sh
    on_success:
      - script: echo 'on success !!!!!'
    on_failure:
      - script: echo 'Failed job .... :('

  - name: build-mexec
    type: runSh
    steps:
      - IN: mexec-repo
      - IN: microbase-img
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/mexec-repo/gitRepo/build.sh
      - OUT: mexec-img
    on_success:
      - script: echo 'on success !!!!!'
    on_failure:
      - script: echo 'Failed job .... :('

  - name: build-microbase
    type: runSh
    steps:
      - IN: microbase-repo
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/microbase-repo/gitRepo/build.sh
      - OUT: microbase-img
    on_success:
      - script: echo 'on success !!!!!'
    on_failure:
      - script: echo 'Failed job .... :('

  - name: build-rp
    type: runSh
    steps:
      - IN: rp-repo
      - IN: microbase-img
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/rp-repo/gitRepo/build.sh
      - OUT: rp-img
    on_success:
      - script: echo 'on success !!!!!'
    on_failure:
      - script: echo 'Failed job .... :('

  - name: build-rdsbase
    type: runSh
    steps:
      - IN: rdsbase-repo
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/rdsbase-repo/gitRepo/build.sh
      - OUT: rdsbase-img
    on_success:
      - script: echo 'on success !!!!!'
    on_failure:
      - script: echo 'Failed job .... :('

  - name: man-rds
    type: manifest
    steps:
      - IN: rdsbase-img

  - name: deploy-beta-rds
    type: deploy
    steps:
      - IN: man-rds
      - IN: beta-rds-docOpts
      - IN: beta-clust
      - IN: beta-rds-lb
        applyTo:
          - manifest: man-rds  # manifest that contains image to connect to
            image: rdsbase-img # img to connect to inside the above manifest
            port: 6379         # containerPort to connect to
      - TASK: managed
        deployMethod: upgrade

  - name: build-nexec
    type: runSh
    steps:
      - IN: nexec-repo
      - IN: microbase-img
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/nexec-repo/gitRepo/build.sh
      - OUT: nexec-img
    on_success:
      - script: echo 'on success !!!!!'
    on_failure:
      - script: echo 'Failed job .... :('

  - name: man-nexec
    type: manifest
    steps:
      - IN: nexec-img

  - name: deploy-beta-nexec
    type: deploy
    steps:
      - IN: man-nexec
      - IN: beta-docOpts
      - IN: beta-prm
      - IN: beta-clust

  - name: build-api
    type: runSh
    steps:
      - IN: api-repo
      - IN: microbase-img
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/api-repo/gitRepo/build.sh
      - OUT: api-img
    on_success:
      - script: echo 'on success !!!!!'
    on_failure:
      - script: echo 'Failed job .... :('

  - name: man-api
    type: manifest
    steps:
      - IN: api-img
      - IN: api-params

  - name: deploy-beta-api
    type: deploy
    steps:
      - IN: man-api
      - IN: beta-api-scaler
      - IN: beta-bitbuc-params
      - IN: beta-braintree-prms
      - IN: beta-db-prms
      - IN: beta-aws-prms
      - IN: beta-api-docOpts
      - IN: beta-prm
      - IN: beta-clust
      - IN: beta-api-lb
        applyTo:
          - manifest: man-api
            image: api-img
            port: 443
      - TASK: managed
        deployMethod: upgrade

  - name: build-api-server
    type: runSh
    flags:
      - shippable-server
    steps:
      - IN: api-server-repo
      - IN: microbase-img
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/api-server-repo/gitRepo/build.sh
      - OUT: api-server-img
    on_success:
      - script: echo 'on success !!!!!'
    on_failure:
      - script: echo 'Failed job .... :('

  - name: build-www-server
    type: runSh
    flags:
      - shippable-server
    steps:
      - IN: www-server-repo
      - IN: microbase-img
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/www-server-repo/gitRepo/build.sh
      - OUT: www-server-img
    on_success:
      - script: echo 'on success !!!!!'
    on_failure:
      - script: echo 'Failed job .... :('

  - name: build-www
    type: runSh
    steps:
      - IN: www-repo
      - IN: microbase-img
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/www-repo/gitRepo/build.sh
      - OUT: www-img
    on_success:
      - script: echo 'on success !!!!!'
    on_failure:
      - script: echo 'Failed job .... :('

  - name: man-www
    type: manifest
    steps:
      - IN: www-img
      - IN: www-params

  - name: deploy-beta-www
    type: deploy
    steps:
      - IN: man-www
      - IN: beta-www-docOpts
      - IN: beta-prm
      - IN: beta-clust
      - IN: beta-www-lb
        applyTo:
          - manifest: man-www
            image: www-img
            port: 443
      - TASK: managed
        deployMethod: upgrade

  - name: build-micro
    type: runSh
    steps:
      - IN: micro-repo
      - IN: microbase-img
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/micro-repo/gitRepo/build.sh
      - OUT: acs-img
      - OUT: autod-img
      - OUT: barge-img
      - OUT: braintree-img
      - OUT: certgen-img
      - OUT: charon-img
      - OUT: cron-img
      - OUT: dcl-img
      - OUT: ddc-img
      - OUT: ec2-img
      - OUT: ecs-img
      - OUT: email-img
      - OUT: gke-img
      - OUT: hipchat-img
      - OUT: hubspotSync-img
      - OUT: irc-img
      - OUT: ini-img
      - OUT: iscan-img
      - OUT: isync-img
      - OUT: jobRequest-img
      - OUT: jobTrigger-img
      - OUT: marshaller-img
      - OUT: nf-img
      - OUT: slack-img
      - OUT: stepExec-img
      - OUT: sync-img
      - OUT: timeTrigger-img
      - OUT: triton-img
      - OUT: versionTrigger-img
      - OUT: webhook-img
    on_success:
      - script: echo 'on success !!!!!'
    on_failure:
      - script: echo 'Failed job .... :('

  - name: man-nf
    type: manifest
    steps:
      - IN: nf-img
      - IN: nf-params

  - name: man-slack
    type: manifest
    steps:
      - IN: slack-img
      - IN: slack-params

  - name: man-email
    type: manifest
    steps:
      - IN: email-img
      - IN: email-params

  - name: man-hipchat
    type: manifest
    steps:
      - IN: hipchat-img
      - IN: hipchat-params

  - name: man-irc
    type: manifest
    steps:
      - IN: irc-img
      - IN: irc-params

  - name: man-webhook
    type: manifest
    steps:
      - IN: webhook-img
      - IN: webhook-params

  - name: deploy-beta-notify
    type: deploy
    steps:
      - IN: man-nf
      - IN: man-slack
      - IN: man-email
      - IN: man-hipchat
      - IN: man-irc
      - IN: man-webhook
      - IN: beta-docOpts
      - IN: beta-prm
      - IN: beta-clust

  - name: man-barge
    type: manifest
    steps:
      - IN: barge-img
      - IN: barge-params

  - name: man-acs
    type: manifest
    steps:
      - IN: acs-img
      - IN: acs-params

  - name: man-autod
    type: manifest
    steps:
      - IN: autod-img
      - IN: autod-params

  - name: man-dcl
    type: manifest
    steps:
      - IN: dcl-img
      - IN: dcl-params

  - name: man-ddc
    type: manifest
    steps:
      - IN: ddc-img
      - IN: ddc-params

  - name: man-ecs
    type: manifest
    steps:
      - IN: ecs-img
      - IN: ecs-params

  - name: man-gke
    type: manifest
    steps:
      - IN: gke-img
      - IN: gke-params

  - name: man-triton
    type: manifest
    steps:
      - IN: triton-img
      - IN: triton-params

  - name: deploy-beta-pv1
    type: deploy
    steps:
      - IN: man-barge
      - IN: man-acs
      - IN: man-autod
      - IN: man-dcl
      - IN: man-ddc
      - IN: man-ecs
      - IN: man-gke
      - IN: man-triton
      - IN: beta-docOpts
      - IN: beta-prm
      - IN: beta-clust

  - name: man-charon
    type: manifest
    steps:
      - IN: charon-img
      - IN: charon-params

  - name: man-deploy
    type: manifest
    steps:
      - IN: stepExec-img
      - IN: deploy-params
      - IN: deploy-scaler

  - name: man-manifest
    type: manifest
    steps:
      - IN: stepExec-img
      - IN: manifest-params

  - name: man-release
    type: manifest
    steps:
      - IN: stepExec-img
      - IN: release-params

  - name: man-rSync
    type: manifest
    steps:
      - IN: stepExec-img
      - IN: rSync-params
      - IN: beta-bitbuc-params

  - name: man-timeTrigger
    type: manifest
    steps:
      - IN: timeTrigger-img
      - IN: timeTrigger-params

  - name: man-versionTrigger
    type: manifest
    steps:
      - IN: versionTrigger-img
      - IN: versionTrigger-params

  - name: deploy-beta-pv2
    type: deploy
    steps:
      - IN: man-charon
      - IN: man-deploy
      - IN: man-manifest
      - IN: man-release
      - IN: man-rSync
      - IN: man-timeTrigger
      - IN: man-versionTrigger
      - IN: beta-docOpts
      - IN: beta-prm
      - IN: beta-clust

  - name: man-sync
    type: manifest
    steps:
      - IN: sync-img
      - IN: sync-params
      - IN: beta-bitbuc-params

  - name: man-marshaller
    type: manifest
    steps:
      - IN: marshaller-img
      - IN: marshaller-params

  - name: man-jobTrigger
    type: manifest
    steps:
      - IN: jobTrigger-img
      - IN: jobTrigger-params

  - name: man-jobRequest
    type: manifest
    steps:
      - IN: jobRequest-img
      - IN: jobRequest-params
      - IN: beta-bitbuc-params

  - name: man-hubspotSync
    type: manifest
    steps:
      - IN: hubspotSync-img
      - IN: hubspotSync-params

  - name: man-cron
    type: manifest
    steps:
      - IN: cron-img
      - IN: cron-params

  - name: man-certgen
    type: manifest
    steps:
      - IN: certgen-img
      - IN: certgen-params

  - name: man-braintree
    type: manifest
    steps:
      - IN: braintree-img
      - IN: braintree-params

  - name: deploy-beta-core
    type: deploy
    steps:
      - IN: man-braintree
      - IN: man-certgen
      - IN: man-cron
      - IN: man-hubspotSync
      - IN: man-jobRequest
      - IN: man-jobTrigger
      - IN: man-marshaller
      - IN: man-sync
      - IN: beta-docOpts
      - IN: beta-prm
      - IN: beta-clust

  - name: man-ini
    type: manifest
    steps:
      - IN: ini-img
      - IN: ini-params

  - name: man-ec2
    type: manifest
    steps:
      - IN: ec2-img
      - IN: ec2-params

  - name: deploy-beta-ci
    type: deploy
    steps:
      - IN: man-ec2
      - IN: man-ini
      - IN: beta-docOpts
      - IN: beta-prm
      - IN: beta-clust

  - name: man-isync
    type: manifest
    steps:
      - IN: isync-img
      - IN: isync-params

  - name: man-esync
    type: manifest
    steps:
      - IN: isync-img
      - IN: esync-params

  - name: man-iscan
    type: manifest
    steps:
      - IN: iscan-img
      - IN: iscan-params

  - name: deploy-beta-scan
    type: deploy
    steps:
      - IN: man-isync
      - IN: man-esync
      - IN: man-iscan
      - IN: beta-docOpts
      - IN: beta-prm
      - IN: beta-clust

  - name: shippable-rel
    type: release
    steps:
      - IN: shippable-ver
        switch: off
      - IN: deploy-beta-ci
        switch: off
      - IN: deploy-beta-core
        switch: off
      - IN: deploy-beta-pv2
        switch: off
      - IN: deploy-beta-pv1
        switch: off
      - IN: deploy-beta-notify
        switch: off
      - IN: deploy-beta-rds
        switch: off
      - IN: deploy-beta-www
        switch: off
      - IN: deploy-beta-api
        switch: off
      - IN: deploy-beta-nexec
        switch: off
      - IN: deploy-beta-scan
        switch: off
      - IN: trigger-product-release
      - TASK: managed
        bump: patch

  ##########################
  # begin Shippable Server jobs
  ##########################
  - name: build-micro-server
    type: runSh
    flags:
      - shippable-server
    steps:
      - IN: micro-server-repo
      - IN: microbase-img
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/micro-server-repo/gitRepo/build.sh
      - OUT: braintree-server-img
      - OUT: certgen-server-img
      - OUT: charon-server-img
      - OUT: cron-server-img
      - OUT: ec2-server-img
      - OUT: email-server-img
      - OUT: hipchat-server-img
      - OUT: hubspotSync-server-img
      - OUT: irc-server-img
      - OUT: ini-server-img
      - OUT: jobRequest-server-img
      - OUT: jobTrigger-server-img
      - OUT: marshaller-server-img
      - OUT: nf-server-img
      - OUT: slack-server-img
      - OUT: stepExec-server-img
      - OUT: sync-server-img
      - OUT: timeTrigger-server-img
      - OUT: versionTrigger-server-img
      - OUT: webhook-server-img
    on_success:
      - script: echo 'on success !!!!!'
    on_failure:
      - script: echo 'Failed job .... :('



  - name: man-braintree-server
    type: manifest
    flags:
      - shippable-server
    steps:
      - IN: braintree-server-img

  - name: man-certgen-server
    type: manifest
    flags:
      - shippable-server
    steps:
      - IN: certgen-server-img

  - name: man-charon-server
    type: manifest
    flags:
      - shippable-server
    steps:
      - IN: charon-server-img

  - name: man-cron-server
    type: manifest
    flags:
      - shippable-server
    steps:
      - IN: cron-server-img

  - name: man-ec2-server
    type: manifest
    flags:
      - shippable-server
    steps:
      - IN: ec2-server-img

  - name: man-email-server
    type: manifest
    flags:
      - shippable-server
    steps:
      - IN: email-server-img

  - name: man-hipchat-server
    type: manifest
    flags:
      - shippable-server
    steps:
      - IN: hipchat-server-img

  - name: man-hubspotSync-server
    type: manifest
    flags:
      - shippable-server
    steps:
      - IN: hubspotSync-server-img

  - name: man-irc-server
    type: manifest
    flags:
      - shippable-server
    steps:
      - IN: irc-server-img

  - name: man-ini-server
    type: manifest
    flags:
      - shippable-server
    steps:
      - IN: ini-server-img

  - name: man-jobRequest-server
    type: manifest
    flags:
      - shippable-server
    steps:
      - IN: jobRequest-server-img

  - name: man-jobTrigger-server
    type: manifest
    flags:
      - shippable-server
    steps:
      - IN: jobTrigger-server-img

  - name: man-marshaller-server
    type: manifest
    flags:
      - shippable-server
    steps:
      - IN: marshaller-server-img

  - name: man-nf-server
    type: manifest
    flags:
      - shippable-server
    steps:
      - IN: nf-server-img

  - name: man-slack-server
    type: manifest
    flags:
      - shippable-server
    steps:
      - IN: slack-server-img

  - name: man-stepExec-server
    type: manifest
    flags:
      - shippable-server
    steps:
      - IN: stepExec-server-img

  - name: man-sync-server
    type: manifest
    flags:
      - shippable-server
    steps:
      - IN: sync-server-img

  - name: man-timeTrigger-server
    type: manifest
    flags:
      - shippable-server
    steps:
      - IN: timeTrigger-server-img

  - name: man-versionTrigger-server
    type: manifest
    flags:
      - shippable-server
    steps:
      - IN: versionTrigger-server-img

  - name: man-webhook-server
    type: manifest
    flags:
      - shippable-server
    steps:
      - IN: webhook-server-img

  - name: man-api-server
    type: manifest
    flags:
      - shippable-server
    steps:
      - IN: api-server-img

  - name: man-www-server
    type: manifest
    flags:
      - shippable-server
    steps:
      - IN: www-server-img

  ###########################################
  # package all server images into one release
  ###########################################

  - name: shippable-server-rel
    type: release
    flags:
      - shippable-server
    steps:
      - IN: shippable-server-ver
        switch: off
      - IN: man-nexec
        switch: off
      - IN: man-www-server
        switch: off
      - IN: man-api-server
        switch: off
      - IN: man-webhook-server
        switch: off
      - IN: man-versionTrigger-server
        switch: off
      - IN: man-timeTrigger-server
        switch: off
      - IN: man-sync-server
        switch: off
      - IN: man-stepExec-server
        switch: off
      - IN: man-slack-server
        switch: off
      - IN: man-nf-server
        switch: off
      - IN: man-marshaller-server
        switch: off
      - IN: man-jobTrigger-server
        switch: off
      - IN: man-jobRequest-server
        switch: off
      - IN: man-ini-server
        switch: off
      - IN: man-irc-server
        switch: off
      - IN: man-hubspotSync-server
        switch: off
      - IN: man-hipchat-server
        switch: off
      - IN: man-email-server
        switch: off
      - IN: man-ec2-server
        switch: off
      - IN: man-cron-server
        switch: off
      - IN: man-charon-server
        switch: off
      - IN: man-certgen-server
        switch: off
      - IN: man-braintree-server
        switch: off
      - IN: trigger-server-release
      - TASK: managed
        bump: patch

  ###########################################
  # push server release to special repo
  ###########################################

  - name: push-release
    type: runSh
    flags:
      - shippable-server
    steps:
      - IN: beta-config-repo
        switch: off
      - IN: docker-creds
        switch: off
      - IN: shipbits-ecr
        switch: off
      - IN: shippable-server-rel
        switch: off
      - TASK:
        - script: echo 'updating packages' && sudo apt-get update
        - script: echo 'installing jq and awscli' && sudo apt-get install -y jq python3-botocore awscli
        - script: aws --version
        - script: docker --version
        - script: ./IN/beta-config-repo/gitRepo/pushRelease.sh
    on_success:
      - script: echo 'succeeded'
    on_failure:
      - script: echo 'failed'
